vich_uploader:
    db_driver: orm

    mappings:
        servico_foto:
            uri_prefix: /images/servicos
            upload_destination: '%kernel.project_dir%/public/images/servicos'
            namer: 
                service: Vich\UploaderBundle\Naming\Base64Namer
                options: {lenght: 8}
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true
    
        usuario_foto:
            uri_prefix: /images/perfil
            upload_destination: '%kernel.project_dir%/public/images/perfil'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    
        configuracao_logo:
            uri_prefix: /images/empresas
            upload_destination: '%kernel.project_dir%/public/images/empresas'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    
